name: Build and Package

on:
  push:
    tags:
      - 'v[0-9].[0-9].[0-9]*'
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            artifact_name: gamepad_tester_linux_x86_64
            executable: gamepad_tester
          - os: windows-latest
            artifact_name: gamepad_tester_windows_x86_64
            executable: gamepad_tester.exe
          - os: macos-latest
            artifact_name: gamepad_tester_macos_arm64
            executable: gamepad_tester

    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Get latest tag
        id: get_tag
        shell: bash
        run: |
          git fetch --tags --force --prune-tags
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "tag=$LATEST_TAG" >> $GITHUB_OUTPUT

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwayland-dev libxkbcommon-dev \
          xorg-dev libegl1-mesa-dev libvulkan-dev libdecor-0-dev

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Build AppImage
        if: runner.os == 'Linux'
        run: |
          wget -c "https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage"
          chmod +x linuxdeploy-x86_64.AppImage

          mkdir -p AppDir/usr/bin
          mkdir -p AppDir/usr/share/applications
          mkdir -p AppDir/usr/share/icons/hicolor/scalable/apps

          cp build/${{ matrix.executable }} AppDir/usr/bin/
          cp assets/gamepad_tester.desktop AppDir/usr/share/applications/
          cp assets/gamepad_tester.svg AppDir/usr/share/icons/hicolor/scalable/apps/

          export ARCH=x86_64
          ./linuxdeploy-x86_64.AppImage --appdir AppDir --output appimage

      - name: Package (Unix)
        if: runner.os != 'Windows'
        run: |
          tar -czvf ${{ matrix.artifact_name }}.tar.gz -C build ${{ matrix.executable }}

      - name: Package (Windows)
        if: runner.os == 'Windows'
        run: |
          Compress-Archive -Path build\Release\${{ matrix.executable }} -DestinationPath ${{ matrix.artifact_name }}.zip

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_type == 'tag' && github.ref_name || steps.get_tag.outputs.tag }}
          files: |
            *.tar.gz
            *.zip
            *.AppImage
          prerelease: ${{ contains(github.ref_name, 'alpha') || contains(github.ref_name, 'beta') || contains(github.ref_name, 'rc') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
